window.DATA = window.DATA || [];
window.DATA = window.DATA.concat([
    {
        "id": 21,
        "area": 16.7,
        "name": "Полет",
        "cost": 3.843,
        "zone": "flight",
        "flat": "Машиноместо №276",
        "image": "./img/filter/parking/pic-11.svg",
    },
    {
        "id": 22,
        "area": 16.7,
        "name": "Полет",
        "cost": 3.658,
        "zone": "flight",
        "flat": "Машиноместо №277",
        "image": "./img/filter/parking/pic-22.svg",
    },
    {
        "id": 23,
        "area": 13.5,
        "name": "Факел",
        "cost": 1.93,
        "zone": "fakel",
        "flat": "Машиноместо №330",
        "image": "./img/filter/parking/pic-33.svg",
    },
    {
        "id": 24,
        "area": 13.5,
        "name": "Факел",
        "cost": 1.875,
        "zone": "fakel",
        "flat": "Машиноместо №332",
        "image": "./img/filter/parking/pic-44.svg",
    },
    {
        "id": 25,
        "area": 14.2,
        "name": "Собрание 21",
        "cost": 2.362,
        "zone": "event",
        "flat": "Машиноместо №27",
        "image": "./img/filter/parking/pic-55.svg",
    },
    {
        "id": 26,
        "area": 13.8,
        "name": "Собрание 21",
        "cost": 4.139,
        "zone": "event",
        "flat": "Машиноместо №121",
        "image": "./img/filter/parking/pic-66.svg",
    },
    {
        "id": 27,
        "area": 13.3,
        "name": "Дивный сад",
        "cost": 4.047,
        "zone": "garden",
        "flat": "Машиноместо №120",
        "image": "./img/filter/parking/pic-77.svg",
    },
    {
        "id": 28,
        "area": 16.4,
        "name": "Дивный сад",
        "cost": 4.52,
        "zone": "garden",
        "flat": "Машиноместо №131",
        "image": "./img/filter/parking/pic-88.svg",
    }
]);
